### ISSUE TITLE
Quasar Mapboxgl is not defined

### ISSUE THREAD

**Issue by Grapetoast** [phegman/vue-mapbox-gl#15]
The webpage version works fine but when working with quasar it throws a mapboxgl is not defined when loading your component. Specifically on the map init function. If you would like to see the error yourself, feel free to clone https://github.com/Screen-Art-Studios/Total-Response-Android 
The map is at the /call endpoint login with user@gmail.com and 123abc as password. click call to display map but as soon as the call page loads it sends the error.

**Comment by phegman** [comment]
Hi,

This is because this package does not include mapbox-gl. This is so users can decide how they would like to pull it in.

You need to include the mapbox-gl javascript file and the css file for it to work correctly (from the docs):

This package does not include the Mapbox GL JS and CSS files. They need to be included in the <head> of your HTML file. See Mapbox GL quickstart guide here: [https://www.mapbox.com/mapbox-gl-js/api/](https://www.mapbox.com/mapbox-gl-js/api/)

If you decide to pull in Mapbox GL via npm and use a module bundler you need to require it globally from your main js file like this: window.mapboxgl = require('mapbox-gl');
