### ISSUE TITLE
Vue popups - undefined parent

### ISSUE THREAD

**Issue by ModernMats** [phegman/vue-mapbox-gl#24]
In one of the given examples you're opening a Vue component (by extending) from a popup. I'm trying to open a modal in the main window (through this https://www.npmjs.com/package/vue-js-modal) through a popup done as your example. Thought it could be done either by emitting an event (like this https://jsfiddle.net/dangvanthanh/3m6s54qx/) or by finding the parent of the Vue popup component. However, it seems like the popup component has no parent and somehow is standing totally by itself. Why is that? What is the relationship between the map component, the popup component and the "larger" component (i.e. the actual view component that export default {} "talks" to)? Sorry if my lingo is a bit weird. 
Seems like it can't by done by doing a new Vue({}) or Vue.component({}) either instead of a Vue.extend({}). What Vue component is it that you're extending through this example?

**Comment by phegman** [comment]
No problem, I think I am following! Unfortunately because Mapbox GL JS injects the popup node into the DOM after initial render it is not indexed by Vue.js so we need to dynamically mount a component using `$mount`. My understanding is a dynamically mounted component does not have a parent so listening for custom events from the root (or other components) will not work. You could use Vuex or an [Event Bus](https://vuejs.org/v2/guide/components.html#Non-Parent-Child-Communication) in this case. Or if you want to show some information about a map point in a modal you could skip using the Mapbox GL JS popup all together and just launch the modal using something like this:

```javascript
mapClicked(map, e) {
  this.addPopUp(map, e);
},
addPopUp(map, e) {
  const features = map.queryRenderedFeatures(e.point, {
    layers: ['points']
  });
  if (!features.length) {
    return;
  }

  const feature = features[0];
  
  //Emit event to open modal here and pass it the `feature`
}
```

If you do decide to go the route of dynamically mounting a component and using an Event Bus or Vuex here is an example of extracting the PopupContent component to its own `.vue` file which cleans it up quite a bit: https://github.com/phegman/vue-mapbox-gl/issues/22

I hope that is helpful!
Pete

**Comment by ModernMats** [comment]
Thanks Pete, It really did!
